version: 2

sources: 
  - name: raw
    schema: gz_raw_data
    description: raw data of greenweez sales, product and shipping data
    tables:
      - name: sales
        identifier: raw_gz_sales
      - name: product
        identifier: raw_gz_product
      - name: ship
        identifier: raw_gz_ship